services:
  wordpress:
    image: mywp6.7.2-php8.1-apache-fa:1.0.0
    restart: always
    ports:
      - 8999:80
    # volumes:
    #   - ./wordpress1:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
    networks:
      - wp-network

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress    
    expose:
      - 3306
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
